### PR TITLE
Fix to send Shipping Method object instead of shipping method as string

### PR DESCRIPTION
**Pull request by nagakri**
MakeShipper method expects Shipping Object, however, it's currently passing string value.  The method getOrder()->getShippingMethod(true) returns shipping object containing carrier code and shipping method.

### CODE REVIEW

**Comment by jaywilliams** [comment]
@ebanolopes This pull-request needs to get merged into the repository, as we were dealing with this very bug on our Magento2 instance and had to patch it manually.

The error message we were getting looks like this:
> Fatal Error: 'Uncaught Error: Call to a member function getCarrierCode() on string in [...]/vendor/signifyd/module-connect/Helper/PurchaseHelper.php:762\nStack trace:\n#0 [...]/vendor/signifyd/module-connect/Helper/FulfillmentHelper.php(230): [...]

**Comment by ebanolopes** [comment]
Hello, @nagakri, thanks for your contribution. We've fixed this with a different approach, but this it is not merged to master branch yet. This will be merged during our next version release, 4.2.0, which must take place before the end of this month.

Meanwhile, if you or @jaywilliams are using version 4.1.0, you can use the patch on below link:
https://osfglobalinc-my.sharepoint.com/:u:/g/personal/ebano_lopes_osf_digital/EVtHyzayUmtFqufeHFr5YSQBW3zP63ENpDs3qw6meBN8yQ?e=fw6syG

These are the modifications done to fix this issue: https://github.com/signifyd/magento2/compare/MAG-672

**Comment by jaywilliams** [comment]
Thanks @ebanolopes, I reviewed your fix, and it looks great. Thanks for getting this bugfix merged in quickly. I'll have composer lock onto `dev-master` for now until an official release has been made.

**Comment by ebanolopes** [comment]
@nagakri @jaywilliams the fix it is now released on 4.1.1

**Comment by jaywilliams** [comment]
@ebanolopes the composer.json version wasn't bumped with the release, neither was etc/module.xml.

**Comment by ebanolopes** [comment]
Thanks, @jaywilliams, now it is :)

**Pull request closed without merging**
